services:
  php:
    build: .
    image: nbt-php74
    platform: linux/amd64
    container_name: nbt-php74
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./routes:/var/www/html/routes
      - ./config:/var/www/html/config
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./sql:/var/www/html/sql
      - ./tests:/var/www/html/tests

  nginx:
    image: nginx:1.27
    container_name: nbt-web
    ports:
      - "8082:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  redis:
    image: redis:7
    container_name: nbt-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  rabbitmq:
    image: rabbitmq:4-management
    container_name: nbt-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: nbt-mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "i&V9WUPOj=27"
    ports:
      - "1433:1433"

